# Generated by Django 2.2.3 on 2021-02-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.CharField(help_text='编码规则：变长，最大长度8位。其中，一级指标占2位，二级指标2位，三级指标2位，四级指标2位。', max_length=8, primary_key=True, serialize=False, verbose_name='编号')),
                ('index_name', models.CharField(help_text='指标名称', max_length=100, verbose_name='指标名称')),
                ('parent_id', models.CharField(help_text='如果是一级指标，则该字段值为00', max_length=100, verbose_name='上级指标')),
                ('description', models.CharField(blank=True, help_text='对指标解决说明（支撑点）', max_length=100, verbose_name='指标说明')),
                ('param', models.DecimalField(blank=True, decimal_places=4, help_text='ax，a为参数，值固定，小数位占4位。', max_digits=5, verbose_name='参数')),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=100, verbose_name='备注')),
            ],
            options={
                'db_table': 'tax_index',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(help_text='自增', max_length=8, primary_key=True, serialize=False, verbose_name='编号')),
                ('city', models.CharField(help_text='地市', max_length=20, verbose_name='地市')),
                ('season', models.CharField(help_text='例如202101，2021年第一季度', max_length=20, verbose_name='季度')),
                ('index_value', models.DecimalField(decimal_places=10, help_text='指标值', max_digits=20, verbose_name='指标值')),
                ('memo', models.CharField(help_text='备注', max_length=100, verbose_name='备注')),
                ('index_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'db_table': 'tax_data',
            },
        ),
    ]
