# Generated by Django 2.2.3 on 2021-02-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '指标数据表', 'verbose_name_plural': '指标数据表'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': '指标表', 'verbose_name_plural': '指标表'},
        ),
        migrations.AlterField(
            model_name='data',
            name='index_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='index.Index'),
        ),
        migrations.AlterField(
            model_name='index',
            name='parent_id',
            field=models.ForeignKey(help_text='如果是一级指标，则该字段值为00', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='index.Index', verbose_name='上级指标'),
        ),
    ]
