# Generated by Django 2.2.3 on 2021-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.IntegerField(help_text='例如00,01,12,99', primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
