# Generated by Django 2.2.3 on 2021-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
