# Generated by Django 2.2.3 on 2021-02-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.CharField(help_text='例如00,01,12,99', max_length=2, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(help_text='指标名称', max_length=100, verbose_name='指标名称')),
                ('description', models.CharField(blank=True, help_text='对指标解决说明（支撑点）', max_length=100, verbose_name='指标说明')),
                ('param', models.DecimalField(blank=True, decimal_places=4, help_text='ax，a为参数，值固定，小数位占4位。', max_digits=5, verbose_name='参数')),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=100, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, help_text='如果是一级指标，则该字段值为null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='index.Index', verbose_name='上级指标')),
            ],
            options={
                'verbose_name': '指标表',
                'verbose_name_plural': '指标表',
                'db_table': 'tax_index',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(help_text='自增', max_length=8, primary_key=True, serialize=False, verbose_name='编号')),
                ('city', models.CharField(help_text='地市', max_length=20, verbose_name='地市')),
                ('season', models.CharField(help_text='例如202101，2021年第一季度', max_length=20, verbose_name='季度')),
                ('index_value', models.DecimalField(decimal_places=10, help_text='指标值', max_digits=20, verbose_name='指标值')),
                ('memo', models.CharField(help_text='备注', max_length=100, verbose_name='备注')),
                ('index1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index1_data', to='index.Index', verbose_name='一级类别')),
                ('index2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index2_data', to='index.Index', verbose_name='二级类别')),
                ('index3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index3_data', to='index.Index', verbose_name='三级类别')),
                ('index4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index4_data', to='index.Index', verbose_name='三级类别')),
            ],
            options={
                'verbose_name': '指标数据表',
                'verbose_name_plural': '指标数据表',
                'db_table': 'tax_data',
            },
        ),
    ]
