# Generated by Django 2.2.3 on 2021-02-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210205_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(help_text='例如0,1,12,99', primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(help_text='地市', max_length=20, verbose_name='地市')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='index.City', verbose_name='地市'),
        ),
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.IntegerField(help_text='例如0,1,12,99', primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
