# Generated by Django 2.2.3 on 2021-02-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210205_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '地市表', 'verbose_name_plural': '地市表'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='tax_city',
        ),
    ]
