# Generated by Django 2.2.3 on 2021-02-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210205_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(help_text='例如0,1,12,99', primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
