# Generated by Django 2.2.3 on 2021-02-26 07:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210205_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='index1',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='name', on_delete=django.db.models.deletion.PROTECT, related_name='index1_data', to='index.Index', verbose_name='指标级别'),
        ),
        migrations.AlterField(
            model_name='data',
            name='index2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='name', on_delete=django.db.models.deletion.PROTECT, related_name='index2_data', to='index.Index', verbose_name='指标级别'),
        ),
        migrations.AlterField(
            model_name='data',
            name='index3',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='name', on_delete=django.db.models.deletion.PROTECT, related_name='index3_data', to='index.Index', verbose_name='指标级别'),
        ),
        migrations.AlterField(
            model_name='data',
            name='index4',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='name', on_delete=django.db.models.deletion.PROTECT, related_name='index4_data', to='index.Index', verbose_name='指标级别'),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(help_text='指标名称', max_length=100, unique=True, verbose_name='指标名称'),
        ),
    ]
