# Generated by Django 2.2.3 on 2021-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210226_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='地市', max_length=20, unique=True, verbose_name='地市'),
        ),
    ]
