"""
Django settings for taxation project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'import_export',
    'users',
    'index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taxation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taxation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ["DATABASES_NAME"],
        'HOST': os.environ["DATABASES_HOST"],
        'PORT': 3306,
        'USER': os.environ["SECRET_USER"],
        'PASSWORD': os.environ["SECRET_PASSWORD"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# 设置自定义的用户模型类
AUTH_USER_MODEL = 'users.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'



STATIC_ROOT = os.path.join(BASE_DIR, "static")
SIMPLEUI_DEFAULT_THEME = 'layui.css'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ICON = {
    '地市表': 'fas fa-city',##/index/city/
    '指标表': 'fas fa-tags',##/index/index/
    '指标数据表': 'fas fa-database'##/index/data/
}
# 指标管理 fas fa-cog
# 用户管理 far fa-user far fa-user
# 认证和授权 fas fa-shield-alt fas fa-users-cog
SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'
SIMPLEUI_HOME_ICON = 'fa fa-user'
SIMPLEUI_STATIC_OFFLINE = True

# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['指标管理','树状图','用户权限'],
# 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,
# 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'app':'index',
            'name': '指标管理' ,
            'icon': 'fa fa-cog',
            'models': [{
                'name': '地市表',
                'url': '/index/city/',
                'icon': 'fas fa-city'
            },{
                'name': '指标表',
                'url': '/index/index/',
                'icon': 'fas fa-tags'
            },{
                'name': '指标数据表',
                'url': '/index/data/',
                'icon': 'fas fa-database'
            }
            ]
        },
        {
            'name': '树状图',
            'icon': 'fas fa-project-diagram',
            'url': '/index/tree/',
        },
        # {
        #     'name': '导入数据',
        #     'icon': 'fas fa-list',
        #     'url': '/index/simple_upload/',
        # },
        {
            'app':'user',
            'name': '用户权限' ,
            'icon': 'fas fa-shield-alt',
            'models': [{
                'name': '用户表',
                'url': '/users/user/',
                'icon': 'far fa-user'
            },
            {
                'name': '权限表',
                'url': '/auth/group/',
                'icon': 'fas fa-users-cog'
            }
            ]
        },
    ]
}
# IMPORT_EXPORT_USE_TRANSACTIONS = True
